import type { Metadata } from "next";
import { geistSans, geistMono, cairo } from "../lib/fonts";
import {AuthProvider} from "./context/AuthContext";
import "./globals.css";
import { ToastContainer } from 'react-toastify';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${cairo.variable} antialiased bg-[#FBFBFB]`}>
        {children}
        <ToastContainer />
      </body>
      </AuthProvider>
    </html>
  );
}
